# fly.toml app configuration file generated for stnicholasgr-meili on 2025-07-25T14:49:36-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'stnicholasgr-meili'
primary_region = 'ord'

[build]
  image = 'getmeili/meilisearch:latest'

[env]
  MEILI_DB_PATH = '/meili_data'
  MEILI_ENV = 'production'

[[mounts]]
  source = 'meili_data'
  destination = '/meili_data'

[http_service]
  internal_port = 7700
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
